### ISSUE TITLE
dimension mismatch

### ISSUE THREAD

**Issue by 0merjavaid** [fawazsammani/knowing-when-to-look-adaptive-attention#3]
![image](https://user-images.githubusercontent.com/22716318/52267982-3554f100-295c-11e9-9f8c-27ad0bca6984.png)

**Comment by homelifes** [comment]
Hi @0merjavaid ,
It is saying that the number of pixels are 64 rather than 49. Did you change anything in the code?

**Comment by fawazsammani** [comment]
Hi @0merjavaid ,
It is saying that the number of pixels are 64 rather than 49. Did you change anything in the code?

**Comment by 0merjavaid** [comment]
The problem is with your preprocessing. 
Resizing at time of pre processing is 254 and training and testing assumes 224

**Comment by fawazsammani** [comment]
Hi. Yes you are right. It seems that I posted the old one rather than the modified one. Nevertheless, you may use the below code that I usually work on, it a `.ipynb` file. I will also update the `preprocessing `file. [The file is here](https://drive.google.com/open?id=1erEOF1ADsV77NDxjEePC958chMT8rghD)
